"""empty message

Revision ID: 133ad36882c4
Revises: 56ebf8fc0f1f
Create Date: 2020-09-16 01:19:49.080688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '133ad36882c4'
down_revision = '56ebf8fc0f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Student_answer')
    op.drop_table('Question')
    op.drop_table('Category')
    op.drop_table('Offical_answer')
    op.create_unique_constraint(None, 'category', ['majorid'])
    op.create_unique_constraint(None, 'officalanswer', ['qid'])
    op.create_foreign_key(None, 'officalanswer', 'studentanswer', ['qid'], ['qid'])
    op.create_foreign_key(None, 'officalanswer', 'category', ['majorid'], ['majorid'])
    op.create_unique_constraint(None, 'question', ['qid'])
    op.create_foreign_key(None, 'question', 'officalanswer', ['qid'], ['qid'])
    op.create_foreign_key(None, 'question', 'studentanswer', ['qid'], ['qid'])
    op.create_foreign_key(None, 'studentanswer', 'officalanswer', ['qid'], ['qid'])
    op.create_foreign_key(None, 'studentanswer', 'category', ['majorid'], ['majorid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'studentanswer', type_='foreignkey')
    op.drop_constraint(None, 'studentanswer', type_='foreignkey')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'question', type_='unique')
    op.drop_constraint(None, 'officalanswer', type_='foreignkey')
    op.drop_constraint(None, 'officalanswer', type_='foreignkey')
    op.drop_constraint(None, 'officalanswer', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    op.create_table('Offical_answer',
    sa.Column('qid', sa.INTEGER(), server_default=sa.text('nextval(\'"Offical_answer_qid_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('majorid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer_des', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('qid', name='Offical_answer_pkey'),
    sa.UniqueConstraint('qid', name='Offical_answer_qid_key')
    )
    op.create_table('Category',
    sa.Column('majorid', sa.INTEGER(), server_default=sa.text('nextval(\'"Category_majorid_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('major', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('majorid', name='Category_pkey'),
    sa.UniqueConstraint('major', name='Category_major_key'),
    sa.UniqueConstraint('majorid', name='Category_majorid_key')
    )
    op.create_table('Question',
    sa.Column('qid', sa.INTEGER(), server_default=sa.text('nextval(\'"Question_qid_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('majorid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_des', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('qid', name='Question_pkey'),
    sa.UniqueConstraint('qid', name='Question_qid_key')
    )
    op.create_table('Student_answer',
    sa.Column('qid', sa.INTEGER(), server_default=sa.text('nextval(\'"Student_answer_qid_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('studentid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_ans', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('qid', name='Student_answer_pkey'),
    sa.UniqueConstraint('qid', name='Student_answer_qid_key')
    )
    # ### end Alembic commands ###
