"""empty message

Revision ID: 56ebf8fc0f1f
Revises: d11f4d20a9c4
Create Date: 2020-09-15 23:56:59.828899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ebf8fc0f1f'
down_revision = 'd11f4d20a9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Category', ['majorid'])
    op.create_unique_constraint(None, 'Offical_answer', ['qid'])
    op.create_unique_constraint(None, 'Student_answer', ['qid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Student_answer', type_='unique')
    op.drop_constraint(None, 'Offical_answer', type_='unique')
    op.drop_constraint(None, 'Category', type_='unique')
    # ### end Alembic commands ###
