"""empty message

Revision ID: d11f4d20a9c4
Revises: 3ca191de7bbc
Create Date: 2020-09-15 23:46:59.738832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11f4d20a9c4'
down_revision = '3ca191de7bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('for_job_users')
    op.create_unique_constraint(None, 'Question', ['qid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Question', type_='unique')
    op.create_table('for_job_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='for_job_users_pkey')
    )
    # ### end Alembic commands ###
